import importlib.resources
from enum import StrEnum

from microfvs.utils.template_helpers import classify_template_variables


class FvsKeyfileTemplate(StrEnum):
    """Enumeration of supported Jinja2 Templates for FVS Keyfiles."""

    DEFAULT = (
        importlib.resources.files("microfvs.templates")
        .joinpath("default_keyfile.j2")
        .read_text()
    )

    def get_template_params(self) -> list[str]:
        """Get named parameters that can be injected into template."""
        return classify_template_variables(self.value)


class FvsEventType(StrEnum):
    """Types of FVS events."""

    TREATMENT = "TREATMENT"
    DISTURBANCE = "DISTURBANCE"


class FvsVariant(StrEnum):
    """Enumeration of supported FVS Variants."""

    description: str

    AK = ("AK", "Southeast Alaska and Coastal British Columbia")
    BM = ("BM", "Blue Mountains")
    CA = ("CA", "Inland California and Southern Cascades (ICASCA)")
    CI = ("CI", "Central Idaho")
    CR = ("CR", "Central Rockies")
    CS = ("CS", "Central States")
    EC = ("EC", "East Cascades")
    EM = ("EM", "Eastern Montana")
    IE = ("IE", "Inland Empire")
    KT = ("KT", "Kootenai, Kaniksu, and Tally Lake (KooKanTL)")
    LS = ("LS", "Lake States")
    NC = ("NC", "Klamath Mountains (and northern California)")
    NE = ("NE", "Northeastern US")
    OC = ("OC", "Organon Southwest")
    OP = ("OP", "Organon Pacific Northwest")
    PN = ("PN", "Pacific Northwest Coast")
    SN = ("SN", "Southern US")
    SO = ("SO", "South Central Oregon and Northeast California (SORNEC)")
    TT = ("TT", "Tetons")
    UT = ("UT", "Utah")
    WC = ("WC", "Westside Cascades")
    WS = ("WS", "Western Sierra Nevada")

    def __new__(cls, value: str, description: str):
        """Create a new FvsVariant."""
        obj = str.__new__(cls, value)
        obj._value_ = value
        obj.description = description
        return obj


class FvsOutputTableName(StrEnum):
    """Enumeration of supported FVS Output Tables."""

    # input tables
    FVS_STANDINIT = "fvs_standinit"
    FVS_TREEINIT = "fvs_treeinit"

    # base FVS system tables
    FVS_AFTER_TREATMENT_TREELIST = "fvs_atrtlist"
    FVS_CALIBRATION_STATS = "fvs_calibstats"
    FVS_CASES = "fvs_cases"
    FVS_COMPUTE = "fvs_compute"
    FVS_CUTLIST = "fvs_cutlist"
    FVS_ERROR = "fvs_error"
    FVS_INV_REFERENCE = "fvs_invreference"
    FVS_STATS_SPECIES = "fvs_stats_species"
    FVS_STATS_STAND = "fvs_stats_stand"
    FVS_SUMMARY = "fvs_summary"
    FVS_SUMMARY2 = "fvs_summary2"
    FVS_TREELIST = "fvs_treelist"
    # FVS establishment model tables
    FVS_REGENERATION_HABITAT_TYPE = "fvs_regen_habtype"
    FVS_REGENERATION_INGROWTH = "fvs_regen_ingrowth"
    FVS_REGENERATION_SITE_PREPARATION = "fvs_regen_siteprep"
    FVS_REGENERATION_SPROUTS = "fvs_regen_sprouts"
    FVS_REGENERATION_TALLY = "fvs_regen_tally"
    FVS_STRUCTURE_CLASS = "fvs_strclass"
    # FVS fire and fuels extension tables
    FVS_BURN_REPORT = "fvs_burnreport"
    FVS_CANOPY_PROFILE = "fvs_canprofile"
    FVS_CARBON = "fvs_carbon"
    FVS_CONSUMPTION = "fvs_consumption"
    FVS_DOWN_WOOD_COVER = "fvs_down_wood_cov"
    FVS_DOWN_WOOD_VOLUME = "fvs_down_wood_vol"
    FVS_FUELS = "fvs_fuels"
    FVS_HARVESTED_CARBON = "fvs_hrv_carbon"
    FVS_MORTALITY = "fvs_mortality"
    FVS_POTENTIAL_FIRE = "fvs_potfire"
    FVS_POTENTIAL_FIRE_CONDITIONAL = "fvs_potfire_cond"
    FVS_POTENTIAL_FIRE_EAST = "fvs_potfire_east"
    FVS_SNAG_DETAIL = "fvs_snagdet"
    FVS_SNAG_SUMMARY = "fvs_snagsum"
    # dwarf mistletoe impact model tables
    FVS_DWARF_MISTLETOE_SIZE_SUMMARY = "fvs_dm_sz_sum"
    FVS_DWARF_MISTLETOE_SPECIES_SUMMARY = "fvs_dm_spp_sum"
    FVS_DWARF_MISTLETOE_STAND_SUMMARY = "fvs_dm_stnd_sum"
    # economic analysis extension tables
    FVS_ECONOMIC_HARVEST_VALUE = "fvs_econharvestvalue"
    FVS_ECONOMIC_SUMMARY = "fvs_econsummary"
    # western root disease model tables
    FVS_ROOT_DISEASE_BEETLE = "fvs_rd_beetle"
    FVS_ROOT_DISEASE_DETAIL = "fvs_rd_det"
    FVS_ROOT_DISEASE_SUMMARY = "fvs_rd_sum"
    # climate extension model table
    FVS_CLIMATE = "fvs_climate"
    # additional tables not generated by FVS
    FVS_STAND_STOCK = "fvs_stdstk"


class ResponseContentType(StrEnum):
    """Content Types for MicroFVS API responses."""

    TEXT_PLAIN = "text/plain"
    APPLICATION_JSON = "application/json"
