name: Pytest with Docker

on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t microfvs:FS2024.4
    - name: Run tests inside container
      run: docker run microfvs:FS2024.4 pytest .
